apiVersion: v1
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export default function () {
      http.get('https://litmuschaos.io');
      sleep(1);
    }
kind: ConfigMap
metadata:
  name: litmus-load-test
  namespace: default
