---
apiVersion: k6.io/v1alpha1
kind: LitmusLoad
metadata:
  name: litmus-load-sample
spec:
  parallelism: 4
  arguments: --vus 10 --duration 30s
  script:
    configMap:
      name: "litmus-load-test"
      file: "script.js"
